#SSL
server.port: 8080
server:
  ssl:
    enabled: false

#SPRING
spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/kgraphqldemo?createDatabaseIfNotExist=true&verifyServerCertificate=false&useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: UX303lb#
    driver-class-name: com.mysql.jdbc.Driver